### ISSUE TITLE
Add support for exponents to DoubleLiteral and RandomDouble

### ISSUE THREAD

**Issue by Hedgemon4** [canvas-gamification/canvas-gamification-junit-tests#131]

**Comment by Hedgemon4** [comment]
See https://github.com/canvas-gamification/canvas-gamification-junit-tests/pull/62

**Comment by Opeyem1a** [comment]
This is going to be a regex thing with double literal and random double, maybe look online for a catch all double catcher (which solves the problem for random double), but supporting double literal means we need bounds

**Comment by Hedgemon4** [comment]
This has been separated into two issues (see https://github.com/canvas-gamification/canvas-gamification-junit-tests/issues/317 and https://github.com/canvas-gamification/canvas-gamification-junit-tests/issues/316).
