### ISSUE TITLE
RandomInteger is failing tests when numbers are random multiples of each other

### ISSUE THREAD

**Issue by Hedgemon4** [canvas-gamification/canvas-gamification-junit-tests#299]

**Comment by Hedgemon4** [comment]
See https://github.com/canvas-gamification/canvas-gamification-junit-tests/pull/222

**Comment by Opeyem1a** [comment]
Idea: Implement some kind of optional soft random

**Comment by Opeyem1a** [comment]
```
RandomInteger a = RandomInteger(...)

testSentence() {
    a.softRandom()
}
```

**Comment by Hedgemon4** [comment]
Should be solved by implementing a soft random option (https://github.com/canvas-gamification/canvas-gamification-junit-tests/issues/318)
